### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Auburns/FastNoise#1]
I would like to point out that identifiers like "[`__FASTNOISE_H__`](https://github.com/Auburns/FastNoise/blob/f19ecc4196bc058a405e0db8c9c56ca4654226a6/FastNoise.h#L29)" and "[`_ValueFractalFBM`](https://github.com/Auburns/FastNoise/blob/f19ecc4196bc058a405e0db8c9c56ca4654226a6/FastNoise.h#L123)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Auburns** [comment]
I will work on changing this.

**Comment by Auburns** [comment]
Only private methods contain an underscore before the method name and reading the rule it seems to only apply to external links. Let me know if this is incorrect.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by Auburns** [comment]
That doesn't answer my last question, I realise the header breaks the rules but the methods are private.

**Comment by elfring** [comment]
[It does not matter](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") which identifiers you would like to categorise as private.

**Comment by Auburns** [comment]
Latest commit changes header define

**Comment by elfring** [comment]
Thanks for your renaming of an include guard.

There are [a few update candidates left over](https://github.com/Auburns/FastNoise/commit/e4676d1c94435ae2c5018b638c5ba82656e26748#diff-307f18be0d3ace2b5b1777864bc3b4e9L174 "Update candidate").
