### ISSUE TITLE
What are the min and max values which can be returned ?

### ISSUE THREAD

**Issue by cgiles** [Auburns/FastNoise#18]
Hello,

I'm playing with noise recently, trying to create biomes, and I ended using your great library.

My only issue is I can't found what is the extrem min and max value ( like 0.0 and 1.0, by example)  that the getNoise(...) function returns.

I use the c++ version.

Is it possible to know what it the min and max value we can expect ?

**Comment by Auburns** [comment]
As stated in the wiki:
All outputs are approximately bounded from -1.0 to 1.0, except for distance functions on cellular noise

**Comment by cgiles** [comment]
Thanks I missed this :/
