### ISSUE TITLE
Simplex noise patent issue

### ISSUE THREAD

**Issue by Zylann** [Auburns/FastNoise#2]
Simplex noise is protected by patents, however another implementation exists, which is OpenSimplex.
The only one I found so far in C is this one: https://github.com/smcameron/open-simplex-noise-in-c
Could it be possible to have the OpenSimplex alternative in FastNoise as well?

**Comment by Auburns** [comment]
The simplex noise patent only covers its use in generating images, since FastNoise is aimed more at 3D implementations such as terrain generation I don't feel OpenSimplex is necessary.

**Comment by Zylann** [comment]
by doing more research I found a reddit post and the patent itself (https://www.google.com/patents/US6867776).
You're right! I didn't knew it was limited to image generation :) 
So, are 2D and 4D generation fine too as long as it's not purely for image generation?

**Comment by Auburns** [comment]
If the data generated using simplex noise is used to create meshes not textures as specified in the patent 

> The apparatus includes a mechanism for producing images with texture that do not have visible grid artifacts.

[https://www.google.com/patents/US6867776](https://www.google.com/patents/US6867776) I don't see terrain generation being an issue. Also the patent only covers 3 dimensions and above, 2D is not covered.
