### ISSUE TITLE
Improved 4D Simplex Noise

### ISSUE THREAD

**Issue by Markyparky56** [Auburns/FastNoise#22]
*Not actually usable yet, jumped the gun. Visually the noise output is pretty bad, needs a bit of re-adjusting*
![4d](https://user-images.githubusercontent.com/6587267/37002177-bef3911e-20c0-11e8-909f-f09a114cb9b3.png)
**Looks like I forgot to check `y0` against `w0`** 

I found a way to improve the speed of the 4D Simplex Noise function by removing the lookup table and replacing it with "ranked counters" as used [here](http://weber.itn.liu.se/~stegu/simplexnoise/SimplexNoise.java), which I happened across when reading through the [Simplex noise demystified](http://staffwww.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf) pdf. From my rather basic tests this does have a noticeable speed increase, around 3ns per value faster.

I've committed the changes to my personal fork [here](https://github.com/Markyparky56/FastNoise/commit/500daa94f035ac280ab84298c88b44dc8f5f4d98), and if you want to compare the two speed wise you can use [this commit](https://github.com/Markyparky56/FastNoise/commit/c22f3962c80ea9fc77b53fd318efea84c1ed20ef) which has the two function as `GetSimplex` and `GetSimplexRanked`.

**Comment by Markyparky56** [comment]
Issues fixed, adding the missing `if (y0 > w0)` fixes the nasty mess that is the above image.
[Latest working commit](https://github.com/Markyparky56/FastNoise/commit/763a2c9a45711333ba1a55ddd18f9b1d206e411d)

Image for comparison
![4d](https://user-images.githubusercontent.com/6587267/37003020-7f2ff2d6-20c3-11e8-9fd8-3110cf9e8113.png)

Speed increase is still roughly 3ns, dipping to ~2.5ns, faster per value.

**Comment by Auburns** [comment]
Great, can you make a pull request

**Comment by Markyparky56** [comment]
[Pull Request](https://github.com/Auburns/FastNoise/pull/23)
