### ISSUE TITLE
Ability to forward declare FastNoise enum types

### ISSUE THREAD

**Issue by hugoam** [Auburns/FastNoise#24]
Hey ! First thanks for the great lean library which I intend to use without moderation :)
I just hit an issue though. For reasons related to an engine I develop, and generating reflection data around the types I use, I need to forward declares the types I'm using.
This means, I also need to forward declare the FastNoise types I'm using.

However for two reasons it is impossible to forward declare the NoiseType, FractalType, etc.. enums : 
- the underlying type is not specified
- they are defined inside the FastNoise class, making it impossible to forward declare them

So I'm wondering if you would be willing to consider changing this ?
That would mean, defining these enums outside of the FastNoise class, probably making them scoped enums so that the names don't cause any name clashes with user code, and giving them an underlying type like unsigned int or short int or whatever you see fit.

Something like : 
```C++
enum class NoiseType : unsigned int { Value, ValueFractal, Perlin, PerlinFractal, Simplex, SimplexFractal, Cellular, WhiteNoise, Cubic, CubicFractal };

class FastNoise
{
    //...
```

This would allow me to interface my reflection 100% with your noise library ! Cheers

**Comment by Auburns** [comment]
I don't want to change it in the current version of FastNoise since it would break compatibility, I will definitely consider it in the new version I'm working on though.
