### ISSUE TITLE
Patent Issue

### ISSUE THREAD

**Issue by zauberparacelsus** [Auburns/FastNoise#3]
You may want to replace the Simplex implementation with OpenSimplex.  Simplex noise is encumbered by patents for 3D and higher-dimensional noise (but not 2D noise, curiously).  OpenSimplex uses an alternative implementation that isn't covered by the patent.

There is, I should note, a claim floating around that the Simplex patent is expired in 2005.  This is untrue, 2005 is the year that Simplex was first published.

**Comment by Auburns** [comment]
The simplex noise patent only covers texture generation, using it for generating terrain is not covered by the patent. Since terrain generation is the main use of this library keeping simplex noise is more beneficial thanks to the faster performance when compared to open simplex.

**Comment by zauberparacelsus** [comment]
That is very interesting, I'll need to keep that in mind.

**Comment by photex** [comment]
Bring out yer dead! Sorry to resurrect this however I'm curious given that wording. It could certainly be argued in a court that a texture was required to be generated in order to generate the terrain couldn't it? 
In what way was "texture" defined in the patent?

**Comment by Auburns** [comment]
Here is the patent you can read into it: [https://www.google.com/patents/US6867776](https://www.google.com/patents/US6867776)

I would argue that a texture has a visual representation, an array of floats is not a texture.
