### ISSUE TITLE
Tiling Noise

### ISSUE THREAD

**Issue by JSandusky** [Auburns/FastNoise#4]
The noise methods don't accept any tiling parameters and most noises aren't 4D capable so the library doesn't appear useful for generating tiling noise without distortion (toroid). Correct me if I've made a mistake/missing-something or that's not part of the library's intent.

**Comment by Auburns** [comment]
You could do it with the simplex 4d noise, but you would have to work out the necessary 4d positions yourself and copy some fractal code to 4d if you wanted that. So no the library is not designed to provide tiled noise, but you could still implement it if you do some of the ground work yourself.
