### ISSUE TITLE
No such thing as position warp?

### ISSUE THREAD

**Issue by squishybanana04** [Auburns/FastNoise#5]
I wanted to use position warp but there is no function in the code. I think the documentation meant to say gradient perturb instead of position warp. Is that right?

**Comment by Auburns** [comment]
Yes, sorry. I renamed the functions, I edit the wiki.

**Comment by squishybanana04** [comment]
Wow, that was fast!

**Comment by squishybanana04** [comment]
![1489512371575bc9ac4d76310604be3986148a9737d00](https://cloud.githubusercontent.com/assets/16113308/23913571/ce5a3e7a-08b9-11e7-9abe-d36f15b5c73c.png)
Is it supposed to look like this?
I have default interpolation and a strength of 45 on 1 octave fbm value noise (scale 0.02)

**Comment by squishybanana04** [comment]
```c++
float** value(float offsetX, float offsetY, int w, int h,
              unsigned int octaves = 4, float scale = 0.1,
              FastNoise::FractalType fractalType = FastNoise::FBM,
              float lacunarity = 2.0, float gain = 0.5, bool perturbed = false) {
    
    noise.SetNoiseType(FastNoise::ValueFractal);
    
    setFractalSettings(octaves, scale, fractalType, lacunarity, gain);
    
    //Get the noise
    float** output = 0;
    output = new float*[w];
    for (int x = 0; x < w; x++) {
        output[x] = new float[h];
        for (int y = 0; y < h; y++) {
            if (!perturbed) output[x][y] = noise.GetNoise(x * scale + offsetX, y * scale + offsetY);
            else {
                float xPos = x;
                float yPos = y;
                noise.GradientPerturb(xPos, yPos);
                output[x][y] = noise.GetNoise(xPos * scale + offsetX, yPos * scale + offsetY);
            }
        }
    }

    return equalize(output, 0, 1, w, h);
}
```

**Comment by squishybanana04** [comment]
I fixed it by removing the * scale part

**Comment by Auburns** [comment]
The scale should be used as the noise frequency

**Comment by Auburns** [comment]
I suggest using the FastNoise preview (under releases) to test out different settings. You should probably use different FastNoise objects for perturbing since then you can set frequency independently, you can also use gradient perturb amp.
