### ISSUE TITLE
m_cellularNoiseLookup ownership

### ISSUE THREAD

**Issue by nlguillemot** [Auburns/FastNoise#9]
`FastNoise` has a member `m_cellularNoiseLookup` which is initially a null pointer, and can be set with `SetCellularNoiseLookup`. The problem is that `FastNoise` has a destructor defined as follows:

    ~FastNoise() { delete m_cellularNoiseLookup; }

This leads to a few API design bugs:

* If you make a copy of a FastNoise object with a cellular noise lookup, it'll call `delete` twice on the same pointer. This will likely crash the program.
* If you call `SetCellularNoiseLookup` twice, it'll leak the memory passed to the first call.
* Pointer to a `FastNoise` object allocated on the stack will cause a crash (since it wasn't allocated with `new`).
* The user may not expect that `FastNoise` will delete their pointer, and the user might delete it a second time themselves by accident.

I have recommend two alternative designs to suggest to solve this problem:

## Design 1: Use a smart pointer

Change the type of `m_cellularNoiseLookup` to `std::unique_ptr<FastNoise>` or `std::shared_ptr<FastNoise>`. This will solve all the problems with double-deletion and memory leaks, but will effectively force users to allocate the FastNoise object on the heap. It is not idiomatic to create a smart pointer that points to an object on the stack, so users will probably avoid it.

Changes required:
* Include `<memory>`
* Remove the line `~FastNoise() { delete m_cellularNoiseLookup; }`
* Remove the line `void SetCellularNoiseLookup(FastNoise* noise) { m_cellularNoiseLookup = noise; }`
* Add the line `void SetCellularNoiseLookup(std::unique_ptr<FastNoise> noise) { m_cellularNoiseLookup = move(noise); }`
* Remove the line `FastNoise* GetCellularNoiseLookup() const { return m_cellularNoiseLookup; }`
* Add the line `FastNoise* GetCellularNoiseLookup() const { return m_cellularNoiseLookup.get(); }`

## Design 2: Use a non-owning pointer

To implement this design, simply remove the destructor.

This makes the `FastNoise` object not have ownership of the lifetime of its cellular noise lookup member, so it becomes the API user's responsibility to ensure that the pointer is valid throughout its usage.

I think this would be the simpler solution. It would allow users to pass in a pointer to a stack object. It would also allow `FastNoise` objects to be copied while retaining the same reference to cellular noise lookup. However, it would break existing code that assumes that `FastNoise` will automatically `delete` its cellular noise member.

**Comment by Auburns** [comment]
Design 2 makes sense now that you added the GetCellularNoiseLookup(). So I've pushed this change.
